-- MySQL Script generated by MySQL Workbench
-- Base de Datos ProgSENA - Estructura Completa
-- Adaptada al proyecto existente

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema progsena
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `titulo_programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `titulo_programa` (
  `titpro_id` INT NOT NULL AUTO_INCREMENT,
  `titpro_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`titpro_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `programa` (
  `prog_codigo` INT NOT NULL AUTO_INCREMENT,
  `prog_denominacion` VARCHAR(100) NOT NULL,
  `titulo_programa_titpro_id` INT NOT NULL,
  `prog_tipo` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`prog_codigo`),
  INDEX `fk_programa_titulo_programa_idx` (`titulo_programa_titpro_id` ASC),
  CONSTRAINT `fk_programa_titulo_programa`
    FOREIGN KEY (`titulo_programa_titpro_id`)
    REFERENCES `titulo_programa` (`titpro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `competencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `competencia` (
  `comp_id` INT NOT NULL AUTO_INCREMENT,
  `comp_nombre_corto` VARCHAR(30) NOT NULL,
  `comp_horas` INT NOT NULL,
  `comp_nombre_unidad_competencia` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`comp_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `competxprograma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `compet_programa` (
  `programa_prog_id` INT NOT NULL,
  `competencia_comp_id` INT NOT NULL,
  PRIMARY KEY (`programa_prog_id`, `competencia_comp_id`),
  INDEX `fk_competxprograma_competencia_idx` (`competencia_comp_id` ASC),
  CONSTRAINT `fk_competxprograma_programa`
    FOREIGN KEY (`programa_prog_id`)
    REFERENCES `programa` (`prog_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_competxprograma_competencia`
    FOREIGN KEY (`competencia_comp_id`)
    REFERENCES `competencia` (`comp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `centro_formacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `centro_formacion` (
  `cent_id` INT NOT NULL AUTO_INCREMENT,
  `cent_nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cent_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `instructor` (
  `inst_id` INT NOT NULL AUTO_INCREMENT,
  `inst_nombres` VARCHAR(45) NULL,
  `inst_apellidos` VARCHAR(45) NULL,
  `inst_correo` VARCHAR(45) NULL,
  `inst_telefono` BIGINT(10) NULL,
  `centro_formacion_cent_id` INT NOT NULL,
  PRIMARY KEY (`inst_id`),
  INDEX `fk_instructor_centro_formacion_idx` (`centro_formacion_cent_id` ASC),
  CONSTRAINT `fk_instructor_centro_formacion`
    FOREIGN KEY (`centro_formacion_cent_id`)
    REFERENCES `centro_formacion` (`cent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `coordinacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coordinacion` (
  `coord_id` INT NOT NULL AUTO_INCREMENT,
  `coord_nombre` VARCHAR(45) NOT NULL,
  `centro_formacion_cent_id` INT NOT NULL,
  PRIMARY KEY (`coord_id`),
  INDEX `fk_coordinacion_centro_formacion_idx` (`centro_formacion_cent_id` ASC),
  CONSTRAINT `fk_coordinacion_centro_formacion`
    FOREIGN KEY (`centro_formacion_cent_id`)
    REFERENCES `centro_formacion` (`cent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ficha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ficha` (
  `fich_id` INT NOT NULL AUTO_INCREMENT,
  `fich_numero` VARCHAR(20) NULL,
  `programa_prog_id` INT NOT NULL,
  `instructor_inst_id_lider` INT NOT NULL,
  `fich_jornada` VARCHAR(20) NOT NULL,
  `fich_fecha_ini_lectiva` DATE NULL,
  `fich_fecha_fin_lectiva` DATE NULL,
  `coordinacion_coord_id` INT NOT NULL,
  PRIMARY KEY (`fich_id`),
  INDEX `fk_ficha_programa_idx` (`programa_prog_id` ASC),
  INDEX `fk_ficha_instructor_idx` (`instructor_inst_id_lider` ASC),
  INDEX `fk_ficha_coordinacion_idx` (`coordinacion_coord_id` ASC),
  CONSTRAINT `fk_ficha_programa`
    FOREIGN KEY (`programa_prog_id`)
    REFERENCES `programa` (`prog_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ficha_instructor`
    FOREIGN KEY (`instructor_inst_id_lider`)
    REFERENCES `instructor` (`inst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ficha_coordinacion`
    FOREIGN KEY (`coordinacion_coord_id`)
    REFERENCES `coordinacion` (`coord_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sede` (
  `sede_id` INT NOT NULL AUTO_INCREMENT,
  `sede_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sede_id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ambiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ambiente` (
  `amb_id` VARCHAR(5) NOT NULL,
  `amb_nombre` VARCHAR(45) NULL,
  `sede_sede_id` INT NOT NULL,
  PRIMARY KEY (`amb_id`),
  INDEX `fk_ambiente_sede_idx` (`sede_sede_id` ASC),
  CONSTRAINT `fk_ambiente_sede`
    FOREIGN KEY (`sede_sede_id`)
    REFERENCES `sede` (`sede_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `asignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asignacion` (
  `instructor_inst_id` INT NOT NULL,
  `asig_fecha_ini` DATETIME NOT NULL,
  `asig_fecha_fin` DATETIME NOT NULL,
  `ficha_fich_id` INT NOT NULL,
  `ambiente_amb_id` VARCHAR(5) NOT NULL,
  `competencia_comp_id` INT NOT NULL,
  `asig_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`asig_id`),
  INDEX `fk_asignacion_instructor_idx` (`instructor_inst_id` ASC),
  INDEX `fk_asignacion_ficha_idx` (`ficha_fich_id` ASC),
  INDEX `fk_asignacion_ambiente_idx` (`ambiente_amb_id` ASC),
  INDEX `fk_asignacion_competencia_idx` (`competencia_comp_id` ASC),
  CONSTRAINT `fk_asignacion_instructor`
    FOREIGN KEY (`instructor_inst_id`)
    REFERENCES `instructor` (`inst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignacion_ficha`
    FOREIGN KEY (`ficha_fich_id`)
    REFERENCES `ficha` (`fich_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignacion_ambiente`
    FOREIGN KEY (`ambiente_amb_id`)
    REFERENCES `ambiente` (`amb_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignacion_competencia`
    FOREIGN KEY (`competencia_comp_id`)
    REFERENCES `competencia` (`comp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `detallexasignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `detalle_asignacion` (
  `asignacion_asig_id` INT NOT NULL,
  `detasig_hora_ini` DATETIME NOT NULL,
  `detasig_hora_fin` DATETIME NOT NULL,
  `detasig_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`detasig_id`),
  INDEX `fk_detallexasignacion_asignacion_idx` (`asignacion_asig_id` ASC),
  CONSTRAINT `fk_detallexasignacion_asignacion`
    FOREIGN KEY (`asignacion_asig_id`)
    REFERENCES `asignacion` (`asig_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
